Repository compucorp/civihr-employee-portal-theme, pull requests merged in 2018-06, with the labels that each got.

#357 PCHR-3724: Fix datepicker styling for mobile
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/scss/civihr_default_theme.style.scss
Labels: bug, regression

#353 PCHR-3485: All staff leave calendar
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
Labels: enhancement, new feature

#358 Sync master with staging
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
  civihr_default_theme/scss/base/_variables.scss
  civihr_default_theme/scss/civihr_default_theme.style.scss
  civihr_default_theme/scss/components/_datepicker-angular.scss
  civihr_default_theme/scss/overrides/jquery/_ui-datepicker.scss
  civihr_default_theme/template.php
Labels: release

#361 PCHR-3674: HR Resources Screen Changes
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/scss/components/_admin.scss
  civihr_default_theme/scss/drupal/_view.scss
  civihr_default_theme/scss/pages/_manage-hr-resources.scss
  civihr_default_theme/template.php
Labels: enhancement, new feature
