Repository compucorp/civihr-employee-portal-theme, pull requests merged in 2018-09, with the labels that each got.

#384 PCHR-4162: Update css for SSP T&A app
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
Labels: enhancement

#380 PCHR-3681: Remove hardcoded paths
  civihr_default_theme/template.php
  civihr_default_theme/templates/view/views-view--onboarding-slideshow--page.tpl.php
Labels: enhancement

#383 PCHR-4142: Fix UI select error
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
Labels: bug

#387 Sync master with staging
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/assets/js/civihr_default_theme.script.js
  civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
  civihr_default_theme/scss/base/_variables.scss
  civihr_default_theme/scss/pages/_features-in-civihr.scss
  civihr_default_theme/scss/pages/_onboarding-customization.scss
  civihr_default_theme/scss/pages/_onboarding-wizard.scss
Labels: release
