Repository compucorp/civihr-employee-portal-theme, pull requests merged in 2018-05, with the labels that each got.

#340 PCHR-3644: Sync styles
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
Labels: bug, regression

#338 Sync master with staging
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/includes/footer.inc
  civihr_default_theme/package-lock.json
  civihr_default_theme/package.json
  civihr_default_theme/scss/base/_custom.scss
  civihr_default_theme/scss/base/_variables.scss
  civihr_default_theme/scss/civihr_default_theme.style.scss
  civihr_default_theme/scss/components/_button.scss
  civihr_default_theme/scss/components/_leave-request-record-actions.scss
  civihr_default_theme/template.php
  civihr_default_theme/templates/page/page.tpl.php
  package-lock.json
  package.json
Labels: release

#330 PCHR-3093: Cleanup Shoreditch Partials
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/scss/base/_variables.scss
  civihr_default_theme/scss/civihr_default_theme.style.scss
  civihr_default_theme/scss/components/_datepicker-angular.scss
  civihr_default_theme/scss/overrides/jquery/_ui-datepicker.scss
Labels: enhancement

#350 PCHR-3673: Count of Assigned Task and Documents
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
  civihr_default_theme/template.php
Labels: new feature

#354 PCHR-3703: New page for Managing HR Resources
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/scss/drupal/_view.scss
  civihr_default_theme/scss/pages/_manage-hr-resources.scss
  civihr_default_theme/template.php
Labels: new feature
