Repository compucorp/civihr-employee-portal-theme, pull requests merged in 2018-02, with the labels that each got.

#316 PCHR-3259: Use lint staged for pre-commit linters
  .gitignore
  civihr_default_theme/.gitignore
  package-lock.json
  package.json
Labels: enhancement

#318 PCHR-2592: Reporting UX improvements
  civihr_default_theme/templates/page/page--reports.tpl.php
Labels: enhancement

#315 PCHR-3061: Task and Assignment admin styles
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
Labels: bug, regression

#319 PCHR-3342: Style Users List Page
  civihr_default_theme/assets/css/civihr_default_theme.style.css
  civihr_default_theme/assets/css/civihr_default_theme.style.css.map
  civihr_default_theme/assets/js/civihr_default_theme.script.js
  civihr_default_theme/scss/base/_helpers.scss
  civihr_default_theme/scss/drupal/_form.scss
  civihr_default_theme/scss/drupal/_table.scss
  civihr_default_theme/scss/drupal/_view.scss
  civihr_default_theme/scss/pages/_users-list.scss
  civihr_default_theme/template.php
  package.json
Labels: new feature
